try{

} catch(Exception e) {

} catch(ArithmeticException a) {

}

Erste Exception catched alle Excpetions, zweite wird nie aktiviert.
